//
//  GeneratedHeaderCommentPlugin.swift
//  SwiftKotlinFramework
//
//  Created by Tamir Twina on 1/13/18.
//

import Foundation

public class GeneratedHeaderCommentPlugin : SourceTransformPlugin {
    public func transform(source: String) throws -> String {
        return try transform(source: source, sourceIdentifier: "Not Available")
    }
    
    public func transform(source: String, sourceIdentifier: String?) throws -> String {
        let headerComment = generatedHeaderComment.replacingOccurrences(of: "{{sourceIdentifier}}", with: sourceIdentifier ?? "unknown source")
        return headerComment + source
    }
    
    public var name: String {
        return "Generated header comment"
    }
    
    public var description: String {
        return "Adds generated comment header"
    }
    
    private var generatedHeaderComment: String {
        return
"""
// ==================================================================
//
// Generated from {{sourceIdentifier}}
//
// DO NOT EDIT THIS FILE. GENERATED FILE, EDITS WILL BE OVERWRITTEN
//
// ==================================================================
\n\n    
"""
    }
    
    public init() {}
}
